$ACR_NAME = "user18AbcShopBackend"       # ACR 이름
$ACR_LOGIN_SERVER = "user18AbcShopBackend.azurecr.io"  # 자동 생성되는 주소
$IMAGE_NAME = "hello-world"    # 테스트용 이미지 이름
$IMAGE_TAG = "v1"             # 태그


az acr login --name $ACR_NAME
docker pull mcr.microsoft.com/hello-world
docker tag mcr.microsoft.com/hello-world $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
